package com.skyblock.core;

import com.skyblock.core.accessory.AccessoryManager;
import com.skyblock.core.command.QuestCommand;
import com.skyblock.core.crafting.CraftingCommand;
import com.skyblock.core.crafting.CraftingManager;
import com.skyblock.core.quest.QuestManager;
import com.skyblock.core.auction.AuctionHouseCommand;
import com.skyblock.core.auction.AuctionHouseManager;
import com.skyblock.core.auction.AuctionManager;
import com.skyblock.core.kuudra.KuudraCommand;
import com.skyblock.core.bank.BankManager;
import com.skyblock.core.bazaar.BazaarCommand;
import com.skyblock.core.bazaar.BazaarManager;
import com.skyblock.core.dungeon.DungeonCommand;
import com.skyblock.core.dungeon.DungeonManager;
import com.skyblock.core.enchanting.EnchantingCommand;
import com.skyblock.core.enchanting.EnchantingManager;
import com.skyblock.core.fishing.FishingCommand;
import com.skyblock.core.fishing.FishingManager;
import com.skyblock.core.fishing.TrophyFishingManager;
import com.skyblock.core.garden.GardenCommand;
import com.skyblock.core.garden.GardenManager;
import com.skyblock.core.guild.GuildManager;
import com.skyblock.core.hotm.HOTMCommand;
import com.skyblock.core.hotm.HOTMManager;
import com.skyblock.core.island.IslandCommand;
import com.skyblock.core.island.IslandManager;
import com.skyblock.core.kuudra.KuudraManager;
import com.skyblock.core.mayor.MayorCommand;
import com.skyblock.core.mayor.MayorManager;
import com.skyblock.core.minion.MinionCommand;
import com.skyblock.core.minion.MinionManager;
import com.skyblock.core.party.PartyCommand;
import com.skyblock.core.party.PartyManager;
import com.skyblock.core.pets.PetsCommand;
import com.skyblock.core.pets.PetsManager;
import com.skyblock.core.profile.ProfileCommand;
import com.skyblock.core.profile.ProfileManager;
import com.skyblock.core.reforge.ReforgeCommand;
import com.skyblock.core.reforge.ReforgeManager;
import com.skyblock.core.backpack.BackpackCommand;
import com.skyblock.core.backpack.BackpackManager;
import com.skyblock.core.event.EventCommand;
import com.skyblock.core.event.EventManager;
import com.skyblock.core.chat.ChatCommand;
import com.skyblock.core.chat.ChatManager;
import com.skyblock.core.leaderboard.LeaderboardCommand;
import com.skyblock.core.leaderboard.LeaderboardManager;
import com.skyblock.core.mail.MailCommand;
import com.skyblock.core.mail.MailManager;
import com.skyblock.core.collections.CollectionsCommand;
import com.skyblock.core.collections.CollectionsManager;
import com.skyblock.core.combat.CombatCommand;
import com.skyblock.core.combat.CombatManager;
import com.skyblock.core.coop.CoopCommand;
import com.skyblock.core.coop.CoopManager;
import com.skyblock.core.forge.ForgeCommand;
import com.skyblock.core.forge.ForgeManager;
import com.skyblock.core.foraging.ForagingCommand;
import com.skyblock.core.foraging.ForagingManager;
import com.skyblock.core.trade.TradeCommand;
import com.skyblock.core.trade.TradeListener;
import com.skyblock.core.trade.TradeManager;
import com.skyblock.core.skills.SkillsManager;
import com.skyblock.core.slayer.SlayerCommand;
import com.skyblock.core.slayer.SlayerManager;
import com.skyblock.core.stats.StatsCommand;
import org.bukkit.plugin.java.JavaPlugin;

public final class SkyblockPlugin extends JavaPlugin {

    private static SkyblockPlugin instance;

    public static SkyblockPlugin getInstance() {
        return instance;
    }

    @Override
    public void onEnable() {
        instance = this;
        BankManager bankManager = BankManager.getInstance();
        bankManager.load(getDataFolder());
        MayorManager mayorManager = MayorManager.getInstance();
        mayorManager.load(getDataFolder());
        MayorCommand mayorCommand = new MayorCommand(mayorManager);
        getCommand("mayor").setExecutor(mayorCommand);
        getCommand("mayor").setTabCompleter(mayorCommand);
        AuctionManager.getInstance();
        AuctionHouseManager auctionHouseManager = AuctionHouseManager.getInstance();
        auctionHouseManager.load(getDataFolder());
        AuctionHouseCommand auctionHouseCommand = new AuctionHouseCommand(auctionHouseManager);
        getCommand("auctionhouse").setExecutor(auctionHouseCommand);
        getCommand("auctionhouse").setTabCompleter(auctionHouseCommand);
        BazaarManager bazaarManager = BazaarManager.getInstance();
        bazaarManager.load(getDataFolder());
        BazaarCommand bazaarCommand = new BazaarCommand(bazaarManager);
        getCommand("bazaar").setExecutor(bazaarCommand);
        getCommand("bazaar").setTabCompleter(bazaarCommand);
        DungeonManager dungeonManager = DungeonManager.getInstance();
        dungeonManager.load(getDataFolder());
        DungeonCommand dungeonCommand = new DungeonCommand(dungeonManager);
        getCommand("dungeon").setExecutor(dungeonCommand);
        getCommand("dungeon").setTabCompleter(dungeonCommand);
        IslandManager islandManager = IslandManager.getInstance();
        IslandCommand islandCommand = new IslandCommand(islandManager);
        getCommand("island").setExecutor(islandCommand);
        getCommand("island").setTabCompleter(islandCommand);
        GuildManager.getInstance();
        PartyManager partyManager = PartyManager.getInstance();
        PartyCommand partyCommand = new PartyCommand(partyManager);
        getCommand("party").setExecutor(partyCommand);
        getCommand("party").setTabCompleter(partyCommand);
        GardenManager gardenManager = GardenManager.getInstance();
        gardenManager.load(getDataFolder());
        GardenCommand gardenCommand = new GardenCommand(gardenManager);
        getCommand("garden").setExecutor(gardenCommand);
        getCommand("garden").setTabCompleter(gardenCommand);
        SlayerManager slayerManager = SlayerManager.getInstance();
        slayerManager.load(getDataFolder());
        SlayerCommand slayerCommand = new SlayerCommand(slayerManager);
        getCommand("slay").setExecutor(slayerCommand);
        getCommand("slay").setTabCompleter(slayerCommand);
        getCommand("slayer").setExecutor(slayerCommand);
        getCommand("slayer").setTabCompleter(slayerCommand);
        FishingManager fishingManager = FishingManager.getInstance();
        fishingManager.load(getDataFolder());
        TrophyFishingManager trophyFishingManager = TrophyFishingManager.getInstance();
        FishingCommand fishingCommand = new FishingCommand(fishingManager, trophyFishingManager);
        getCommand("fishing").setExecutor(fishingCommand);
        getCommand("fishing").setTabCompleter(fishingCommand);
        HOTMManager hotmManager = HOTMManager.getInstance();
        hotmManager.load(getDataFolder());
        HOTMCommand hotmCommand = new HOTMCommand(hotmManager);
        getCommand("hotmtree").setExecutor(hotmCommand);
        getCommand("hotmtree").setTabCompleter(hotmCommand);
        PetsManager petsManager = PetsManager.getInstance();
        petsManager.load(getDataFolder());
        PetsCommand petsCommand = new PetsCommand(petsManager);
        getCommand("pets").setExecutor(petsCommand);
        getCommand("pets").setTabCompleter(petsCommand);
        KuudraManager kuudraManager = KuudraManager.getInstance();
        kuudraManager.load(getDataFolder());
        KuudraCommand kuudraCommand = new KuudraCommand(kuudraManager);
        getCommand("kuudra").setExecutor(kuudraCommand);
        getCommand("kuudra").setTabCompleter(kuudraCommand);
        EnchantingManager enchantingManager = EnchantingManager.getInstance();
        enchantingManager.load(getDataFolder());
        EnchantingCommand enchantingCommand = new EnchantingCommand(enchantingManager);
        getCommand("enchanting").setExecutor(enchantingCommand);
        getCommand("enchanting").setTabCompleter(enchantingCommand);
        ReforgeManager reforgeManager = ReforgeManager.getInstance();
        reforgeManager.load(getDataFolder());
        ReforgeCommand reforgeCommand = new ReforgeCommand(reforgeManager);
        getCommand("reforge").setExecutor(reforgeCommand);
        getCommand("reforge").setTabCompleter(reforgeCommand);
        SkillsManager skillsManager = SkillsManager.getInstance();
        skillsManager.load(getDataFolder());
        AccessoryManager.getInstance();
        StatsCommand statsCommand = new StatsCommand(skillsManager, slayerManager);
        getCommand("stats").setExecutor(statsCommand);
        getCommand("stats").setTabCompleter(statsCommand);
        ProfileManager profileManager = ProfileManager.getInstance();
        profileManager.load(getDataFolder());
        ProfileCommand profileCommand = new ProfileCommand(profileManager);
        getCommand("profile").setExecutor(profileCommand);
        getCommand("profile").setTabCompleter(profileCommand);
        MinionManager minionManager = MinionManager.getInstance();
        minionManager.load(getDataFolder());
        MinionCommand minionCommand = new MinionCommand(minionManager);
        getCommand("minion").setExecutor(minionCommand);
        getCommand("minion").setTabCompleter(minionCommand);
        CraftingManager craftingManager = CraftingManager.getInstance();
        craftingManager.load(getDataFolder());
        CraftingCommand craftingCommand = new CraftingCommand(craftingManager);
        getCommand("crafting").setExecutor(craftingCommand);
        getCommand("crafting").setTabCompleter(craftingCommand);
        QuestManager questManager = QuestManager.getInstance();
        questManager.load(getDataFolder());
        QuestCommand questCommand = new QuestCommand(questManager);
        getCommand("quest").setExecutor(questCommand);
        getCommand("quest").setTabCompleter(questCommand);
        TradeManager tradeManager = TradeManager.getInstance();
        TradeCommand tradeCommand = new TradeCommand(tradeManager);
        getCommand("trade").setExecutor(tradeCommand);
        getCommand("trade").setTabCompleter(tradeCommand);
        getServer().getPluginManager().registerEvents(new TradeListener(tradeManager), this);
        BackpackManager backpackManager = BackpackManager.getInstance();
        backpackManager.load(getDataFolder());
        BackpackCommand backpackCommand = new BackpackCommand(backpackManager);
        getCommand("backpack").setExecutor(backpackCommand);
        getCommand("backpack").setTabCompleter(backpackCommand);
        EventManager eventManager = EventManager.getInstance();
        EventCommand eventCommand = new EventCommand(eventManager);
        getCommand("event").setExecutor(eventCommand);
        getCommand("event").setTabCompleter(eventCommand);
        ForagingManager foragingManager = ForagingManager.getInstance();
        foragingManager.load(getDataFolder());
        ForagingCommand foragingCommand = new ForagingCommand(foragingManager);
        getCommand("foraging").setExecutor(foragingCommand);
        getCommand("foraging").setTabCompleter(foragingCommand);
        CombatManager combatManager = CombatManager.getInstance();
        CombatCommand combatCommand = new CombatCommand(combatManager);
        getCommand("combat").setExecutor(combatCommand);
        getCommand("combat").setTabCompleter(combatCommand);
        CollectionsManager collectionsManager = CollectionsManager.getInstance();
        collectionsManager.load(getDataFolder());
        CollectionsCommand collectionsCommand = new CollectionsCommand(collectionsManager);
        getCommand("collections").setExecutor(collectionsCommand);
        getCommand("collections").setTabCompleter(collectionsCommand);
        ChatManager chatManager = ChatManager.getInstance();
        ChatCommand chatCommand = new ChatCommand(chatManager);
        getCommand("chat").setExecutor(chatCommand);
        getCommand("chat").setTabCompleter(chatCommand);
        LeaderboardManager leaderboardManager = LeaderboardManager.getInstance();
        LeaderboardCommand leaderboardCommand = new LeaderboardCommand(leaderboardManager);
        getCommand("leaderboard").setExecutor(leaderboardCommand);
        getCommand("leaderboard").setTabCompleter(leaderboardCommand);
        MailManager mailManager = MailManager.getInstance();
        mailManager.load(getDataFolder());
        MailCommand mailCommand = new MailCommand(mailManager);
        getCommand("mail").setExecutor(mailCommand);
        getCommand("mail").setTabCompleter(mailCommand);
        ForgeManager forgeManager = ForgeManager.getInstance();
        ForgeCommand forgeCommand = new ForgeCommand(forgeManager);
        getCommand("forge").setExecutor(forgeCommand);
        getCommand("forge").setTabCompleter(forgeCommand);
        CoopManager coopManager = CoopManager.getInstance();
        coopManager.load(getDataFolder());
        CoopCommand coopCommand = new CoopCommand(coopManager);
        getCommand("coop").setExecutor(coopCommand);
        getCommand("coop").setTabCompleter(coopCommand);
    }

    @Override
    public void onDisable() {
        AuctionHouseManager.getInstance().save(getDataFolder());
        BankManager.getInstance().save(getDataFolder());
        MayorManager.getInstance().save(getDataFolder());
        BazaarManager.getInstance().save(getDataFolder());
        DungeonManager.getInstance().save(getDataFolder());
        SlayerManager.getInstance().save(getDataFolder());
        FishingManager.getInstance().save(getDataFolder());
        PetsManager.getInstance().save(getDataFolder());
        GardenManager.getInstance().save(getDataFolder());
        HOTMManager.getInstance().save(getDataFolder());
        KuudraManager.getInstance().save(getDataFolder());
        EnchantingManager.getInstance().save(getDataFolder());
        ReforgeManager.getInstance().save(getDataFolder());
        MinionManager.getInstance().save(getDataFolder());
        SkillsManager.getInstance().save(getDataFolder());
        ProfileManager.getInstance().save(getDataFolder());
        CraftingManager.getInstance().save(getDataFolder());
        QuestManager.getInstance().save(getDataFolder());
        BackpackManager.getInstance().save(getDataFolder());
        ForagingManager.getInstance().save(getDataFolder());
        CollectionsManager.getInstance().save(getDataFolder());
        MailManager.getInstance().save(getDataFolder());
        CoopManager.getInstance().save(getDataFolder());
        instance = null;
    }
}
